version: 0.2
env:
  variables:
    NODE_ENV: "production"

phases:
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
    - Dockerrun.aws.json
    - .platform/**/*
