@startuml
title next-iron-session 호출
'actor getInitialProps
actor Browser
actor ProxyApiServer
Browser -> ProxyApiServer:  서비스 호출
ProxyApiServer -> ProxyApiServer: ironSession에서 Token 불러오기
ProxyApiServer -> LoginServer: 토큰 없으면 로그인 페이지 호출
ProxyApiServer -> ServiceAPI: 서비스 호출( access token )
ServiceAPI -> ProxyApiServer: 서비스 응답
ProxyApiServer -> Browser: 서비스 응답
@enduml
