@startuml
title React CRA 호출
Browser -> AuthAPI: 로그인팝업요청
AuthAPI -> Browser: 로그인 팝업 (AuthServer)
Browser -> AuthAPI: 인증정보(ID/PW. AuthServer)
AuthAPI -> Browser: Access, Refresh Token
Browser -> Browser: Store Access Token=>memory
Browser -> Browser: Store Refresh Token=>http only cookie | local storage
Browser -> ServiceAPI: Call With Bearer Access Token
@enduml
