@startuml
title next-auth httpOnly 쿠키 호출
'actor getInitialProps
actor Browser
actor ProxyApiServer
'getInitialProps -> getInitialProps: cookie에서 auth Token 불러오기
'getInitialProps -> LoginPage: 토큰 없으면 로그인 페이지 호출
'getInitialProps -> ServiceAPI: 서비스 호출( access token )
'ServiceAPI -> getInitialProps: 서비스 응답
'getInitialProps -> Browser: initialProps로 서비스 응답 결과
Browser -> ProxyApiServer:  서비스 호출
ProxyApiServer -> ProxyApiServer: httpOnly cookie(samSite:'lax')에서 auth Token 불러오기
ProxyApiServer -> LoginServer: 토큰 없으면 로그인 페이지 호출
ProxyApiServer -> ServiceAPI: 서비스 호출( access token )
ServiceAPI -> ProxyApiServer: 서비스 응답
ProxyApiServer -> Browser: 서비스 응답
@enduml
