@startuml
title auth0 api 호출

actor getInitialProps
actor ClientSide
actor Proxy
getInitialProps -> getInitialProps: auth0.getSession(req)
getInitialProps -> LoginAPI: session 정보 없으면 로그인 API 호출
getInitialProps -> ServiceAPI: 서비스 호출( access token )
ServiceAPI -> getInitialProps: 서비스 응답
getInitialProps -> ClientSide: initialProps로 서비스 응답 결과
ClientSide -> ClientSide: 메모리에 session 정보 불러오기
ClientSide -> LoginAPI: 사용자 없을 경우 로그인 API 호출
ClientSide -> Proxy:  서비스 호출
Proxy -> Proxy: cookie에서 auth Token 불러오기
Proxy -> LoginPage: 토큰 없으면 로그인 페이지 호출
Proxy -> ServiceAPI: 서비스 호출( access token )
ServiceAPI -> Proxy: 서비스 응답
Proxy -> ClientSide: 서비스 응답
@enduml
