@startuml
title 로그인 및 Private Resource 호출

actor 관리자
관리자->Browser : 1. ID/PW 입력. 로그인 클릭
Browser -> Browser : 2. ID/PW 유효성 검사
Browser -> 관리자 : 2-X. 유효성 실패 메시지
Browser -> ProxyApiServer: 3. 로그인 요청 ( ID/PW )
ProxyApiServer -> AuthApiServer: 4. 로그인 요청 ( ID/PW )
AuthApiServer -> ProxyApiServer: 5. 로그인 응답 ( AToken, RToken )
ProxyApiServer -> Browser: 5-X. 로그인 실패
Browser -> 관리자 : 5-X. 로그인 실패 메시지
ProxyApiServer -> ProxyApiServer: 6. 쿠키(토큰정보. A, R Token) 암호화
ProxyApiServer -> ProxyApiServer: 7. 쿠키 저장(헤더 세팅)
ProxyApiServer -> Browser : 8. 로그인 성공 코드(브라우저 쿠키 저장)
Browser -> 관리자 : 9. 로그인 성공 메시지
관리자 -> Browser : 10. Private Data 조회 클릭
Browser -> ProxyApiServer : 11. Private Proxy Api
ProxyApiServer->ProxyApiServer: 12. 쿠키 복호화
ProxyApiServer->ProxyApiServer: 13. 쿠키에 accessToken확인.(기간, 존재 간단 검사).
' 프록시 서버쪽에 jwt 토큰 키를 갖고 토큰 검증 해도 될듯.
ProxyApiServer->ProxyApiServer: 13-X. 쿠키에 refreshToken확인.(기간, 존재 간단 검사).
ProxyApiServer->Browser: 13-X-X. 로그인 페이지로 이동
Browser->관리자:13-X-X. 로그인 페이지
ProxyApiServer->AuthApiServer: 13-X. token refresh 요청.
AuthApiServer->ProxyApiServer: 13-X. token refresh 응답.
ProxyApiServer->ProxyApiServer: 13-X. 6,7 수행. 15번 응답에 새 쿠키 포함
ProxyApiServer->PrivateApiServer:13. Private Api Request with accessToken
PrivateApiServer->ProxyApiServer:14. Private Api Response with accessToken
ProxyApiServer->Browser:15. Private Api Response with accessToken. 새 쿠키 세팅
Browser->관리자:16. Private Data
@enduml
