@startuml
'https://plantuml.com/sequence-diagram

autonumber

인앱 -> 스토어: 제품목록조회
스토어 -> 인앱: 제품목록결과
인앱 -> 인앱: 제품선택
인앱 -> 스토어: 인앱결제요청(제품)
스토어 -> 인앱: 인앱결제응답 (성공/실패)
인앱 -> 백앤드: 인앱결제정보 전송
백앤드 -> 백앤드: 전달받은 내용으로 비즈니스로직 처리
백앤드 -> 인앱: 인앱결제정보 처리 결과
인앱 -> 인앱: 알아서 잘 쓰고 있겠지
group 스토어결제 이벤트 처리
group 정기 결제 발생
스토어 -> 백앤드: 결제 됐어라고 토큰을 전달(webhook)
백앤드 -> 스토어: 토큰으로 자세한 내역을 조회 요청
스토어 -> 백앤드: 자세한 내역 응답
백앤드 -> 백앤드: 응답내용을 토대로 비즈니스로직 처리
end
group 정기 결제 취소
인앱 -> 스토어: 구독 취소(혹은 사용자가 스토어에서 직접 취소)
스토어 -> 백앤드: 구독이 취소됐어 라고 토큰을 전달
백앤드 -> 스토어: 토큰으로 자세한 내역을 조회 요청
스토어 -> 백앤드: 자세한 내역 응답
백앤드 -> 백앤드: 응답내용을 토대로 비즈니스로직 처리
end
end
@enduml