@startuml
title 사용자 정보조회 userMe

actor 사용자
사용자 -> Browser : 페이지 접속
Browser -> "userMe()" : 호출
database localStorage
"userMe()" -> localStorage : 사용자 정보 조회
localStorage --> "userMe()" : 사용자 정보
group 사용자 정보 있을 경우
"userMe()" -> NodeApi : /userMe
NodeApi -> NodeApi : 토큰 decode(accountId)
NodeApi --> "userMe()" : <font color=red><b>토큰 유효성 결과
"userMe()" -> Browser : 사용자정보
Browser -> 사용자 : 사용자정보
else 사용자 정보 없을 경우
database ServiceDB
"userMe()" -> NodeApi : /userMe?all=true
NodeApi -> NodeApi : 토큰 decode(accountId)
NodeApi -> ServiceDB : 사용자 정보 조회(With accountId)
ServiceDB -> NodeApi : 사용자 정보(이름, 이메일, 사용자 PK)
NodeApi -> "userMe()" : 사용자 정보, <font color=red><b>토큰 유효성 결과
"userMe()" -> localStorage : 사용자 정보 저장
"userMe()" -> Browser : 사용자정보
Browser -> 사용자 : 사용자정보
end

group <font color=red>토큰 유효성 결과 에러 처리
else accessToken만료
NodeApi -> "userMe()" : 토큰 유효성 결과 401 Error
"userMe()" -> "localStorageClear()"
"userMe()" -> "refreshToken()"
else refreshToken만료
NodeApi -> "userMe()" : 토큰 유효성 결과401 Error
"userMe()" -> "localStorageClear()"
"userMe()" -> 로그인페이지
end

사용자 -> 로그아웃
로그아웃 ->  "localStorageClear()"

'사용자 -> 로그인페이지
'로그인페이지 ->  "localStorageClear()"
@enduml
